version: '3.8'

services:
  database:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./certify_init.sql:/docker-entrypoint-initdb.d/certify_init.sql
    networks:
      - network
    ports:
      - "5433:5432"

  certify:
    container_name: 'certify-service'
    build: 
      context: ../../certify-service
      dockerfile: Dockerfile
    user: root
    ports:
      - 8090:8090
    environment:
      - container_user=mosip
      - active_profile_env=default, postgres-farmer
      - SPRING_CONFIG_NAME=certify
      - SPRING_CONFIG_LOCATION=/home/mosip/config/
      - enable_certify_artifactory=false
      - download_hsm_client=false
      - mosipbox_public_url=http://certify-nginx:80
    volumes:
      - ./config/certify-default.properties:/home/mosip/config/certify-default.properties
      - ./config/certify-postgres-farmer.properties:/home/mosip/config/certify-postgres-farmer.properties
      - ./data/CERTIFY_PKCS12:/home/mosip/CERTIFY_PKCS12
      # This can be disabled if one uses plugins included in inji-certify-with-plugins docker image.
      - ./loader_path/certify/:/home/mosip/additional_jars/
      # modify the below file to change the identity fields in the VC
      - ./config/farmer_identity_data.csv:/home/mosip/config/farmer_identity_data.csv
    networks:
      - network
    depends_on:
      - database

  certify-nginx:
    image: nginx:stable
    ports:
      - 8091:80
    volumes:
      - ./certify-nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network
    depends_on:
      - certify


  inji-web:
    container_name: 'inji-web'
    image: mosipid/inji-web:0.12.0
    ports:
      - '3001:3004'
    environment:
      - DEFAULT_LANG=en
      - MIMOTO_HOST=https://inji-dev.iugolabs.com/v1/mimoto
    volumes:
      - ./config/mimoto-default.properties:/home/mosip/mimoto-default.properties
      - ./config/mimoto-issuers-config.json:/home/mosip/mimoto-issuers-config.json
      - ./config/mimoto-trusted-verifiers.json:/home/mosip/mimoto-trusted-verifiers.json
      - ./config/credential-template.html:/home/mosip/credential-template.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network
      
networks:
  network:
    name: mosip_network

volumes:
  cache:
    driver: local
